# Generated by Django 3.2.12 on 2022-04-10 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture_occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prix', models.FloatField(null=True)),
                ('Marque', models.CharField(max_length=255)),
                ('Modéle', models.CharField(max_length=255)),
                ('Type_de_chassis', models.CharField(max_length=255)),
                ('Premiére_immatriculation', models.CharField(max_length=255)),
                ('Pays', models.CharField(max_length=255)),
                ('Ville', models.CharField(max_length=255)),
                ('Carburant', models.CharField(max_length=255)),
                ('Année', models.CharField(max_length=255)),
                ('Kilométrage', models.IntegerField()),
                ('Puissance_fiscale', models.IntegerField(null=True)),
                ('Nombre_de_portes', models.IntegerField(default=4)),
                ('Nombre_de_siége', models.IntegerField(null=True)),
                ('Couleur_de_carrosserie', models.CharField(max_length=255)),
                ('Boite_de_vitesse', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50)),
                ('Permis', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, default='sansImageCar.png', upload_to='images/voituresOccasion/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_verification', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_publier', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('ancien', 'ancien'), ('neuf', 'neuf'), ('presq-neuf', 'presq-neuf')], max_length=255)),
                ('prix', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVoitureOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/voituresOccasion/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voiture', to='voiture.voiture_occasion')),
            ],
        ),
    ]
