# Generated by Django 3.2.12 on 2022-04-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='etat',
            field=models.CharField(choices=[('neuf', 'neuf'), ('ancien', 'ancien'), ('presq-neuf', 'presq-neuf')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], default='Homme', max_length=255),
        ),
        migrations.AlterField(
            model_name='voiture_occasion',
            name='Boite_de_vitesse',
            field=models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], max_length=50),
        ),
    ]
