# Generated by Django 3.2.12 on 2022-04-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_auto_20220410_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='etat',
            field=models.CharField(choices=[('presq-neuf', 'presq-neuf'), ('ancien', 'ancien'), ('neuf', 'neuf')], max_length=255),
        ),
    ]
